language: node_js
node_js:
  - "8.10.0"
sudo: true
dist: trusty

branches:
  only:
  - master
  - develop

notifications:
  email:
    on_success: never

script:
  - npm run test
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  on:
    branch: master
